Bei Syntax-Fehlern im XML friert dispatcher jetzt ein statt einen Diff auszulassen.

diff --git a/dispatcher/apply_gz_osc b/dispatcher/apply_gz_osc
--- a/dispatcher/apply_gz_osc
+++ b/dispatcher/apply_gz_osc
@@ -14,9 +14,35 @@ do
   echo "apply_gz_osc($1)@"`date "+%s"`": applying $CURRENT.osc.gz" >>/opt/osm_why_api/dispatcher.log
   echo "apply_gz_osc($1)@"`date "+%s"`": applying $CURRENT.osc.gz"
   gunzip <../hourly/$CURRENT.osc.gz | ./apply_osc --intermediate --db=$1
+  EXITCODE=$?
+  while [[ $EXITCODE -ne 0 ]];
+  do
+  {
+    echo "apply_gz_osc($1)@"`date "+%s"`": apply_osc failed with error code "$EXITCODE >>/opt/osm_why_api/dispatcher.log
+    echo "apply_gz_osc($1)@"`date "+%s"`": apply_osc failed with error code "$EXITCODE
+    sleep 30
+    echo "apply_gz_osc($1)@"`date "+%s"`": applying $CURRENT.osc.gz" >>/opt/osm_why_api/dispatcher.log
+    echo "apply_gz_osc($1)@"`date "+%s"`": applying $CURRENT.osc.gz"
+    gunzip <../hourly/$CURRENT.osc.gz | ./apply_osc --intermediate --db=$1
+    EXITCODE=$?
+  };
+  done
   CURRENT=$(($CURRENT+1))
 };
 done
 echo "apply_gz_osc($1)@"`date "+%s"`": applying $ALMOST_TO.osc.gz" >>/opt/osm_why_api/dispatcher.log
 echo "apply_gz_osc($1)@"`date "+%s"`": applying $ALMOST_TO.osc.gz"
 gunzip <../hourly/$ALMOST_TO.osc.gz | ./apply_osc --db=$1
+EXITCODE=$?
+while [[ $EXITCODE -ne 0 ]];
+do
+{
+  echo "apply_gz_osc($1)@"`date "+%s"`": apply_osc failed with error code "$EXITCODE >>/opt/osm_why_api/dispatcher.log
+  echo "apply_gz_osc($1)@"`date "+%s"`": apply_osc failed with error code "$EXITCODE
+  sleep 300
+  echo "apply_gz_osc($1)@"`date "+%s"`": applying $ALMOST_TO.osc.gz" >>/opt/osm_why_api/dispatcher.log
+  echo "apply_gz_osc($1)@"`date "+%s"`": applying $ALMOST_TO.osc.gz"
+  gunzip <../hourly/$CURRENT.osc.gz | ./apply_osc --db=$1
+  EXITCODE=$?
+};
+done
